### ISSUE TITLE
Training on imagenet

### ISSUE THREAD

**Issue by yhenon** [DT42/squeezenet_demo#2]
Hi, thanks for your work here. Are you planning on training this on Imagenet and releasing the weights ? I'm considering doing this on my end (and have access to Titan X gpus). Unfortunately the Squeezenet paper doesn't contain all the information needed, e.g. the validation split used, the data augmentation, etc.

**Comment by tammyyang** [comment]
Hi yhneon, 

Yes, I do plan to train it on imagenet and release the weight, but yes, not all the information is contained in the paper. So, it might take me some time to figure out the right set of parameters and to complete this task. Since the caffemodel was released, I am also doing the weight conversion to Keras in parallel.

I will definitely share more if I have good progress. Any suggestion or progress sharing from your side is more than welcome :).

Cheers,
Tammy
